### ISSUE TITLE
Two alarm notifications received 

### ISSUE THREAD

**Issue by rhannink** [nlrb/com.visonic.powermax#12]
Hello,

Homey receives 2 messages that an alarm in zone "system" went off after walking into my house.
And Homey is ignoring the entry-delay. It gives an alarm message right away (2x). And the label is "system" instead of "keuken" or "kamer"

Remco

**Comment by nlrb** [comment]
Not exactly sure which triggers you use, but likely closed with app version 1.0.1.

**Comment by rhannink** [comment]
Ok,
Thanks for the fast action/fix. Not sure either why the 2 triggers, not seen them again, will try version 1.0.1 right away.

Gr. Remco

**Comment by jeroenvano** [comment]
Guys - quick question how do I upgrade a local installed app? Do I just use
athom project --install again?


2016-12-23 13:05 GMT+01:00 rhannink <notifications@github.com>:

**Comment by rhannink** [comment]
Yep,

Thats what I did and it worked.

Of course you can also uninstall the app first, but its not necessary I think.

Gr. Remco

**Comment by nlrb** [comment]
Yes, don't uninstall - then you'll lose all your settings. Just update the code and do a `--install` again.

**Comment by jeroenvano** [comment]
Ok, thanks, will give it a try ;) Thanks for the update Ramón

**Comment by rhannink** [comment]
NLRB,

Can I now use the “Zone alarm words active” trigger on Homey and then the “zone” label contains the name of the zone the alarm occurred in?
And now this trigger does not activate on the entry-delay anymore?

Gr. Remco

**Comment by jeroenvano** [comment]
Update worked, have 1.0.1 running now.

Tested:
Speech works now.
In alarm status both entry/exit delay are triggered correctly
No false alarm on entry delay

But zone alarm does not trigger like Remco said.

Regards,
Jeroen

2016-12-23 13:45 GMT+01:00 rhannink <notifications@github.com>:

> NLRB,
>
> Can I now use the “Zone alarm words active” trigger on Homey and then the
> “zone” label contains the name of the zone the alarm occurred in?
> And now this trigger does not activate on the entry-delay anymore?
>
> Gr. Remco
>

**Comment by nlrb** [comment]
@rhannink Yes.
@jeroenvano Zone alarm only triggers when there is an actual alarm (so state armed, zone triggered).

**Comment by jeroenvano** [comment]
That's what I testes an actual alarm. It did not trigger.

Op 23 dec. 2016 16:34 schreef "nlrb" <notifications@github.com>:

@rhannink <https://github.com/rhannink> Yes.
@jeroenvano <https://github.com/jeroenvano> Zone alarm only triggers when
there is an actual alarm (so state armed, zone triggered).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nlrb/com.visonic.powermax/issues/12#issuecomment-269006467>,
or mute the thread

**Comment by rhannink** [comment]
Hello,

I tested the latest version of the app. I made two flows, one triggers when the panel alarm becomes active and one triggers if a zone alarm becomes active.

The first flow triggered after about a minute after the alarm went off ??
The second flow did not trigger at all.

Also the labels inside the flow editor say: Alarm: false and bewegingsalarm: false. during the alarm.
Seems like the alarm is not send directly or at all to Homey (polling issue???)

Gr. Remco

**Comment by nlrb** [comment]
@rhannink It is normal that there is a delay on the actual alarm. The length of the delay depends on how the panel is configured (see parameter 'Alarm delay'/'Alarmvertraging'). There is no polling, communication is event based.

**Comment by rhannink** [comment]
@nlrb Ok, I will try this again, but thats no reason for one off the two flows not giving any alert at all, not even after a few minutes. 

What is the difference between "zone alarm word" action card and the "panel alarm wordt" action card? And what content should the labels "naam" en "zone" get? After an alarm is triggered, these values stay undefined.

Gr. Remco

**Comment by rhannink** [comment]
Hmm, I tested this afternoon but the flow does not trigger when a alarm went off. I reduced the alarm delay to 0 seconds.
When the alarm goes off and I test the flow, the trigger works. But when the alarm goes off, the flow does not trigger. All the tags "Naam" en "zone" are undefined....
![flow_-_homey_and_athom_apps](https://cloud.githubusercontent.com/assets/1661824/21742734/a63472ba-d4f4-11e6-8e0b-eac3ed0a5968.png)

**Comment by nlrb** [comment]
@rhannink That the zone alarm trigger does not work is known (see issue #13 that is open for that). To test a flow you will need to provide values yourself (replace undefined as there are no example values in the app.json). But this of course only tests the 'then' part of the flow.
