### ISSUE TITLE
Alarm off event when apps restarts

### ISSUE THREAD

**Issue by rhannink** [nlrb/com.visonic.powermax#14]
Hello,

Lately, there are a lot of Homey updates. I noticed that after every reboot and after the powermax app restarts, an alarm off event is generated. I created a flow which sends me a push notification when the alarm is turned off.

No big issue, but I now receive a notification after every reboot/update off Homey.

Gr. Remco

**Comment by nlrb** [comment]
Nothing can be done about this. When Homey would be stable, there would be no issue.
