### ISSUE TITLE
wiring and config

### ISSUE THREAD

**Issue by chrisns** [nlrb/com.visonic.powermax#17]
Hi,
Please could you advise to the pin wiring you used to the USR-TCP232-302 from a dual rs232 module?
Also could you advise to the config of the USR-TCP232-302?
Many thanks

**Comment by nlrb** [comment]
Config:
Parity/data/stop: NONE 8 1
Baudrate: 9600
Work mode: TCP Server

Pinout:
RJ45 (8 pin)   - DB9 (F)
3 (TXD) black  - 2 (RXD)
5 (GND) green  - 5 (GND)
6 (RXD) yellow - 3 (TXD)
