### ISSUE TITLE
[Feature Request]. Wired Motion Sensors Support

### ISSUE THREAD

**Issue by Javiast** [nlrb/com.visonic.powermax#19]
Hello nlrb,

just an enhancement request to be considered for futurele realease of the powermax app. Could you please add support for motioin wired detectors, please?. Notice that battery and tamper indications are not needed in this kind of sensor.

Many thanks
JAvier

**Comment by Javiast** [comment]
Hi Ramon,

Testing. So far so good, I can now add me two wired sensor and everything
seems to work like a charm. See picture. I keep it running and let you know
if there is any thing wrong.


MANY THANKS AGAIN!!!
Javier

**Comment by nlrb** [comment]
Hi Javier,

I don't see any picture, but good to hear it works!

Best regards,
-Ramón

**Comment by Javiast** [comment]
[image: pmwired2.jpg][image: pmwired1.jpg]Quick finger :-)

Sending pictures now
Javier
