### ISSUE TITLE
[Feature Request]. Retrival of Event Log

### ISSUE THREAD

**Issue by Javiast** [nlrb/com.visonic.powermax#20]
Helllo nlrb,

I don't really want to abuse, but it will be really nice if the powermax app were able to retrieve the full event log  from the panel, Could you please add this enhancement in the wish list for future new release of your nice application?

Many thanks in advance
Javier

**Comment by Javiast** [comment]
Ramon, 1.3.0!!! testing now. It is show nice (see piecture)
Many thanks. Ramon.

Two comments:

-. Event logs retrival won't work unless you use usr #1
I had created a fake user in the panel to configure it in the powermax app
"user to arm/disarm" . I realized that unless you use user #1,  panel will
reply with a Denied message.
I'll check if there is any way to configure user privileges in the panel.
I'll let you know if I find anything.
This is not a big deal, however it has to be documented.

17:32:29.503 [192.168.1.190:23] PDU sent to panel: 0d a0 00 00 00 75 19 00
00 00 00 00 43 8d 0a
17:32:29.540 [192.168.1.190:23] Start of new PDU detected ; Expecting 02 a0
17:32:29.543 [192.168.1.190:23] Message 0x02; incomingPduLen = 0
17:32:29.547 [192.168.1.190:23] PDU received 0d 02 43 ba 0a
17:32:29.552 [192.168.1.190:23] Start of new PDU detected ; Expecting a0
17:32:29.556 [192.168.1.190:23] Message 0x08; incomingPduLen = 0
17:32:29.559 [192.168.1.190:23] PDU received 0d 08 43 b4 0a
17:32:29.565 [192.168.1.190:23] PDU sent to panel: 0d 02 fd 0a
17:32:29.569 [192.168.1.190:23] Handling DENIED message (160)


- I still get memory crashes in the application. I'm almost sure it related
to the way wired sensors behave.
Contrary to the the wireless sensor (which get in sleep mode for a period
of time after a movement detection) , the wired sensor will keep reporting
movement to the panel.
My guessing now is that, memorywise,  if homey/the application cannot
manage well so many events. Seems not to be memory leak issue, as if avoid
sending movement events application will star releasing memory.
I keep testing, but just to let you that wired sensor support can become
more tricky that it appears.

Cheers,
Javier



[image: imagen.png]

**Comment by nlrb** [comment]
Hi Javier,

On item 1: I should indeed not use the arming user pin code (which is configurable in the app settings), but I can use the installer pin code instead.

On item 2: There is nothing specific for wired sensors. If there is a memory leak, it will always be there. Unfortunately I don't see it with the two panels I have. However, since 1.5 more people/apps are reporting memwarn issues (see https://github.com/athombv/nl.philips.hue/issues/79 and https://github.com/athombv/homey/issues/1776).

Best regards,
-Ramón

BTW: don't know what you do to add images, but it doesn't work

**Comment by Javiast** [comment]
Hi Ramon,

I'm using google inbox and it seems it doesn't like pasting picture I had
to attched them as a file. Picture below now :-)

I'll keep testing the memwarns issues and let you know my findings.

Cheers
Javier

[image: imagen.png]
