### ISSUE TITLE
Fetching log data is not working

### ISSUE THREAD

**Issue by rhannink** [nlrb/com.visonic.powermax#22]
Hello,

Just installed version 1.3.0 via developer tools. Everything works fine, but the new feature of retrieving the log files doesn't work. After pressing the button, the status changes to "Data wordt opgehaald..." and it stays this way. I waited more then 5 minutes, but nothing changed. I have a Powermax+ panel.

Gr. Remco

**Comment by nlrb** [comment]
Hi Remco,

Can you try the latest code changes and see if that works better for you?

Grt,
-Ramón

**Comment by rhannink** [comment]
Perfecto Ramón,

The latest version is showing the logs from the Powermax+ panel.
Thanks again for your good work and fast respons.

Gr. Remco

![settings_-_homey](https://user-images.githubusercontent.com/1661824/31054188-8d4fe4a6-a6ad-11e7-818b-05ff5f6f24a1.png)
