### ISSUE TITLE
Armed Home Instant state

### ISSUE THREAD

**Issue by rpbras** [nlrb/com.visonic.powermax#25]
Please can you add the possibility to activate the Armed Home Instant state?
I'm using the Powermax+ Rev.F.

Thnx in advance.
Raymond

**Comment by nlrb** [comment]
How would you want to use this?
a) from the mobile card. If so, would an app setting be OK to arm normal or arm instant?
b) from a flow
c) both?

**Comment by rpbras** [comment]
If it's possible both.

Met vriendelijke groet,
Raymond en Miranda Bras

2018-03-07 20:14 GMT+01:00 Ramón Baas <notifications@github.com>:

**Comment by rpbras** [comment]
Sorry, I missed the second question on a. But maybe you you can add an extra button in the mobile card or make a long press activate an instant alarm?

Thnx in advance.

**Comment by rpbras** [comment]
Beste Ramon,

heb je al enig idee wanneer de optie voor directe inschakeling beschikbaar
is?

Alvast bedankt voor je reactie.

Met vriendelijke groet,
Raymond

Met vriendelijke groet,
Raymond en Miranda Bras

2018-03-07 20:51 GMT+01:00 Raymond en Miranda <rpbras@gmail.com>:

**Comment by nlrb** [comment]
Please give it a try before I update the docs.

**Comment by rpbras** [comment]
Thanks, but can you explain me how to install your latest version with instant arm implemented?

Kind regards,
Raymond

Verzonden vanuit Mail voor Windows 10

Van: Ramón Baas
Verzonden: donderdag 26 juli 2018 10:57
Aan: nlrb/com.visonic.powermax
CC: rpbras; Author
Onderwerp: Re: [nlrb/com.visonic.powermax] Armed Home Instant state (#25)

Please give it a try before I update the docs.

**Comment by nlrb** [comment]
Search Youtube for “Homey CLI”.

**Comment by rpbras** [comment]
I’ve installed version 1.4 succesfully. But I don’t see any changes in de flow cards.
Do I have te re-install the alarm panel?

Verzonden vanuit Mail voor Windows 10

Van: Ramón Baas
Verzonden: donderdag 26 juli 2018 13:43
Aan: nlrb/com.visonic.powermax
CC: rpbras; Author
Onderwerp: Re: [nlrb/com.visonic.powermax] Armed Home Instant state (#25)

Search Youtube for “Homey CLI”.

**Comment by nlrb** [comment]
Crap! How did that code get lost? Will have to do that over again. At least you can arm it instant from the UI by setting the device option.

**Comment by rpbras** [comment]
Thnx for the efforts to make this version. It seems to work well.
I'm still testing and will contact you when I know more.
