### ISSUE TITLE
[Feature request] Bypassing Zones

### ISSUE THREAD

**Issue by jeroenvano** [nlrb/com.visonic.powermax#27]
Hi Ramon,

Would it be possible to add flows to by pass zones before arming the alarm?

Regards,
Jeroen

**Comment by nlrb** [comment]
Hi Jeroen,

I only notice your request now. Yes, I can add it to the flow as an action. Up to you then when to execute the bypass :-).

Grtz,
-R.

**Comment by jeroenvano** [comment]
Hi Ramon,

Just installed the latest github version but I am unable to find how to add the bypass in a flow.
enabling/disabling the sensor has been selected in the panel, but the sensor cards do not have action in flows to be bypassed or disabled. I removed and added one window sensor to be sure I used the latest driver.

Any tips ?

Regards,
Jeroen

**Comment by nlrb** [comment]
What type of sensor did you drag to the 'then' part?

**Comment by nlrb** [comment]
BTW: if you look at lines 1250-1272 in app.json you see the bypass related actions defined.

**Comment by jeroenvano** [comment]
I tried to disable a window/door sensor. 
Can you give a flow example?

**Comment by nlrb** [comment]
![image](https://user-images.githubusercontent.com/11725674/43655933-e0ccb750-9750-11e8-8f21-bf82eaeea578.png)

Make sure you do a CTRL-R (refresh) in your browser or Homey app, otherwise you won't see the new cards!

**Comment by jeroenvano** [comment]
Had to re-install the latest github version, now I also have the new action cards to build a flow.
In the tags "enabled" or "aangezet" does not change (stays on yes) for the device after running the flow to disable? This should indicate if the sensor is currently enabled or disabled right?

**Comment by nlrb** [comment]
Yes, indeed. I see the tag change when enabling/disabling a sensor. If it does not change, your panel settings probably disallow it. But then it also does not work with the mobile cards.

**Comment by jeroenvano** [comment]
Ok, it does not change so I need to figure out how to allow it in the panel
settings. Thanks!

**Comment by nlrb** [comment]
See section 4.4.8 of the manual.

**Comment by jeroenvano** [comment]
Thanks for the hint in the manual, I have it working now :) Sweet!
