### ISSUE TITLE
Is there already a early stage SDKv2 version of the App ?

### ISSUE THREAD

**Issue by mruiter** [nlrb/com.visonic.powermax#28]
Hello Weledele Heer,

I know youre a busy gentlemen , but i was wondering if there's already a early version of a SDKv2 version of the beloved PowerMax app.
I can do some testing in the new firmware V2 enviroment also.

**Comment by nlrb** [comment]
Hi Marco,

There is no v2 version yet. I first want to move the other apps over, but I'm not really spending any time on the Athom apps lately.
Thanks for the offer though. BTW: I though you had stopped using the Visonic alarm and moved to z-wave sensors only?

Grtz,
-Ramón

**Comment by mruiter** [comment]
Not zwave alone . I have a redundant setup with powermax and heimdall . Both can use each other to trigger and guard the house

But most sensors are indeed zwave and zigbee but also 10 on powermax 

Verstuurd vanaf mijn iPhone

**Comment by konradwalsh** [comment]
> Hi Marco,
> 
> There is no v2 version yet. I first want to move the other apps over, but I'm not really spending any time on the Athom apps lately.
> Thanks for the offer though. BTW: I though you had stopped using the Visonic alarm and moved to z-wave sensors only?
> 
> Grtz,
> -Ramón

I would love if you could get this done.. I understand you are busy though

**Comment by nlrb** [comment]
Moving v2 discussion to #29.
