### ISSUE TITLE
[BOUNTY] Visonic SDK v2 Compatibility Work

### ISSUE THREAD

**Issue by konradwalsh** [nlrb/com.visonic.powermax#29]
I am hoping with this thread to provide the motivation for @nlrb to upgrade the Visonic app. He did a great job creating it. Now, it would be great for it to work with SDK v2.
I have no idea how much work is involved, but without his app, my install is pretty useless with the new 2.0.
Therefore, I would propose a bounty to assist him.
I am offering €20 euro. If @nlrb comes back and says there is significant work then I will gladly up my bounty.
Are there others willing to support this?

**Bounty currently stands at**

**€20 - Konrad Walsh** - @KonradWalsh 
**€20 - Raymondh** - @Raymond 
**€20 - jeroenvano** - @jeroenvano 
**€20 - MarcoRuiter** - @MarcoRuiter 
**€20 - Javier** - @jmieres
**€20 - Gr. Remco** - @rhannink
**Total - €120**

https://community.athom.com/t/bounty-20-visonic-sdk-v2-compatibility-work/5242

**Comment by konradwalsh** [comment]
FYI
Bounty already at €60

**Comment by jeroenvano** [comment]
Hi Ramón - just to let you know that I am also backing this (jeroenvano). You know everyone loves your app and that is why at least some of us are willing to spend some money for your effort to upgrade to SDK2.

**Comment by nlrb** [comment]
Appreciate the support guys, but it is time I need :-). Hopefully I get some time to work on this during the Christmas holidays. Still rely on one of you to then test it on FW 2.0.x, since I'm not planning to move over soon.

**Comment by konradwalsh** [comment]
Well.. its just gone up to 80€ so you'll just have to give up on sleep!

As far as testing goes, I am in the best position now since I've just moved house and my network is broken now.

**Comment by konradwalsh** [comment]
€100! of faith in you

**Comment by konradwalsh** [comment]
120 euro!

**Comment by silbernagel** [comment]
@nlrb -- Is it ok to add to the bounty for purchase of another homey? I've no interest in this plugin, but if it helps the wireless weather app, I'm all in!

**Comment by jwikman** [comment]
@konradwalsh add another 20€ from me. 

I don't need this app, but I really want an update of the wireless weather app. I'm already on FW2.0, so I live with all quirkiness right now.

If we could gather enough € to cover for a new Homey that Ramón could use for development, I assume that it's getting easier to develop apps that works on FW2.0. Don't you think @nlrb ?

**Comment by nlrb** [comment]
Is it important to keep 100% backward compatibility? I'm thinking of moving all separate sensors (motion, magnet, smoke, etc.) into one sensor type. It still would look the same, but is different under the hood. Advantage would be e.g. that you can pair all sensors at once from one list. Downside would be that existing sensors would need to be removed and re-paired.

**Comment by konradwalsh** [comment]
Either works as long as we can still individually react to each Motion
sensor etc

**Comment by konradwalsh** [comment]
Although.. For apps like heimdall having separate properly classed devices
is best

**Comment by silbernagel** [comment]
I say you can kill backward compatibility. Some times you need to update things.

**Comment by mruiter** [comment]
A repair of all the devices is something youre userbase is happy to do . Good to see you found Some time . 🎉 that 20 euros are burning in my pocket 😉

**Comment by rhannink** [comment]
Ading all sensors Again is no problem at all. Must say, the app is working for me on 2.0 but haven’t tried removing/addding or changing something. Good to hear You found time to pick it up again.

**Comment by konradwalsh** [comment]
That's odd cause it doesn't work for me on 2.0

**Comment by konradwalsh** [comment]
Interestingly.. @rhannink comment got me thinking..
So I removed my panel from homey and readded it and yes it works..
It does give errors when saving settings but works nonetheless

**Comment by konradwalsh** [comment]
The biggest issue I see is that flows don't work.. Now you have to select a panel that the flow applies too

**Comment by nlrb** [comment]
Well, there is a new branch available. As it is a major rewrite, it still requires extensive testing though (and I'll probably do some more tweaks).

**Comment by konradwalsh** [comment]
Excellent...

Will start testing now

**Comment by konradwalsh** [comment]
OK.. so no major issues.. 
Did re-add all devices
Settings Page loads with logs visible
Will start checking out flows in more detail now

**Comment by konradwalsh** [comment]
So I have had 3 crashes in 3 days..

Seems to happen when we set the alarm from within Homey.. there is an error regarding the Promise Response...

Otherwise.. seems reasonably stable


EDIT:
I hadn't noticed you committed new versions.. I will update my installed version and report back

**Comment by nlrb** [comment]
@konradwalsh Indeed please update. There have been some important changes (including the Promise fix).

**Comment by Javiast** [comment]
Hello, 
I'm still in Homey FW v1.5.13.
Will it help if I start testing the new SDK2 version ?

**Comment by Brendvm** [comment]
No rush, just curious. Is there any news to report for this app regarding homey v2? How is testing going and any chance of this app hits the app store (maybe as a beta).

**Comment by mruiter** [comment]
Looks 2 me everything works except one thing.
The Powermax panel status changed trigger cards dont seem to work.
So status has changed to Activated , Deactivated or partial activated dont seem to trigger the flows.

The status tchanged trigger card with a tag that gets filled does seem to work.

**Comment by nlrb** [comment]
@mruiter Thanks for testing. Can you add a screen shot of which one does not work for you? This one works for me:
![image](https://user-images.githubusercontent.com/11725674/51087550-15fbe700-1755-11e9-979d-cad1479fc12a.png)

**Comment by nlrb** [comment]
@Brendvm I'll first need to update the docs & images before it can be submitted to the app store. But the code should be in reasonably good order now.

**Comment by mruiter** [comment]
Hello Ramón,

I guess its the same card but then under Homey V2







Maybee someone else can test these cards to on Homey V2 ?

These seem to be the only cards or function in the app that dont seem to be working in testing the new app for me 

Verstuurd vanaf mijn iPhone

**Comment by nlrb** [comment]
Hi Marco, well, that explains it. That is a default capability, so I cannot fix this in the app. Probably Athom has forgotten to implement this one in v2. Wouldn’t be the first time 😄 .

**Comment by mruiter** [comment]
Mmm then i have to use the status changed with a and tag is i guess since thats youre code .

Would not be the first time indeed 😝

Verstuurd vanaf mijn iPhone

**Comment by Brendvm** [comment]
I am not on v2 yet, so can't tell. Soon as this app becomes officialy available i'm going to update. Thanks to @nlrb for all your time and effort.

**Comment by moores211** [comment]
when i open the visonic app on the v2 homey app it just says event log - how do i add my panel? thanks
all where do i send 20 euros? this is the main thing that stops me going back to vera!

**Comment by mruiter** [comment]
Just add a new device . Type powermax 
Just like how you would add a zwave hue or other device 

Verstuurd vanaf mijn iPhone

**Comment by rpbras** [comment]
If I update to v2 do all my flows with the Visonic app still work?

**Comment by nlrb** [comment]
@rpbras No. You will need to add new sensors and remove the old ones. Flows with sensors will need to be repaired.

**Comment by rpbras** [comment]
Ok, thnx.
And thnx for rewriting the app.
How can I sent you the 20 euro?

Kind regards,
Raymond

Op do 17 jan. 2019 21:44 schreef Ramón Baas <notifications@github.com:

**Comment by rpbras** [comment]
> @rpbras No. You will need to add new sensors and remove the old ones. Flows with sensors will need to be repaired.

Ok, thnx.
And thnx for rewriting the app.
How can I sent you the 20 euro?

Kind regards,
Raymond

**Comment by nlrb** [comment]
There will be a donate button on the app page.

**Comment by rpbras** [comment]
How many of you already changed over to Homey v2 and used the Visonic app? And what are your experiences?

**Comment by rhannink** [comment]
I am using Homey 2.0 but still with the old app. I have read that the change status card is not working yet. And thats what I am using in flows. ....

**Comment by mruiter** [comment]
You can just use the state change cards with a tag . Only the native homey cards dont work but the developer Made his own cards .
He already knew Athom usualy drivers half broken goods ;) 

Verstuurd vanaf mijn iPhone

**Comment by rpbras** [comment]
I thought the old app didn’t work on v2?

**Comment by rhannink** [comment]
You cant change any setting. But everything else is working...

**Comment by rhannink** [comment]
I just installed the v2.0.0 version, everything seems okay, I have made a pull request for the missing icons in the panel. I use flows with labels and they work fine. I did not have to re-add the panel, just the sensors.......

Can I already donate as promised?

**Comment by rhannink** [comment]
When I try to save the advanced settings of the panel, I get an error (unable to save the settings, unknown error). 

I can only send you a diagnostic report when the app is from the App Store. Not when installed via athom-cli

**Comment by mruiter** [comment]
Are you sure you are using the master master code and not a second later added installer code ?
The second added master code doesn’t allow you to save alarm settings from serial and gives a error . I think you are trying to give homey the right to disarm the system ?

Verstuurd vanaf mijn iPhone

**Comment by rhannink** [comment]
Yep, I am sure I use the correct master code. I get an unknown error every time I try to save the advanced settings. I did not add the panel with the new app, only the sensors...Might this have something to do with it ?

**Comment by nlrb** [comment]
@rhannink The panel device has not changed. So this should still work as before (it does for me). Can you attach a screenshot of the error you get? Do the run the app with `run` and see any logging?

**Comment by rhannink** [comment]
This I the error I get:

![img_4040](https://user-images.githubusercontent.com/1661824/51635793-ea001300-1f57-11e9-958e-9cdb186311a6.PNG)

The log file shows no entries after trying to save.

**Comment by rhannink** [comment]
@nlrb I ran the app from the command line with atom app run. I saw a lot off debug coming by. No errors, everything looks alright. When I set the mastercode and I save it, I get the red error in the app, but absolutely noting in the debug log on my computer. So it looks like a local app problem. Nothing is sent to the Powermax and the PowerMax does not generate any errors at the moment I press save.

Is it correct that after entering the master code you use the arrow back < and then press save? 

I am 100% sure the master code is the correct one. Also tried reinstalling the app, same problem.

**Comment by konradwalsh** [comment]
I had an issue with a voice command that caused the app the crash repeatedly and then homey to restart...

I believe it's more to do with voice than the app..

Nonetheless there is a screenshot I caught
![screenshot_20190124-221340_homey](https://user-images.githubusercontent.com/7996482/51747731-4a02d080-20a2-11e9-9623-83add1636b56.jpg)

**Comment by rpbras** [comment]
I'm using the 'old' app under Homey v2. Everything is working as it should. Saving changed settings (inschakelen zonder uitschakelen turned on) created an error while saving (the red error), but the settings were saved which I can see when activating the alarm. It's now always 'directe inschakeling'.

**Comment by nlrb** [comment]
@konradwalsh I'll create a separate issue for that. It is strange that there are no triggers, but I should check for that and prevent a crash.

**Comment by konradwalsh** [comment]
So.. for me this has been very stable. No issues or show stoppers. Once it gets into the appstore, I am happy to donate

**Comment by rhannink** [comment]
Are you able to change and save the advanced settings? This is the only problem I have. Rest is very stable indeed.

**Comment by mruiter** [comment]
The only ones that had trouble with that got it working by double checking the installer code . When you setup you’re powermax you have to said 1 super god installer code . After that most create a normal installer mode.
For the advanced settings like arm and disarm powermax you need the super god installer code . The normal installer code doesn’t seem to have the right. So double check and search you’re docs you made if you have any for that first god code

Verstuurd vanaf mijn iPhone

**Comment by nlrb** [comment]
I did find & fix some bugs this week, but good to hear to works stable.
Regarding updating the device settings - it does work, but you get the annoying 'unknown error'. There is no way around this. Will need to submit a case with Athom for that.

**Comment by mruiter** [comment]
Ramón , when will you add the PayPal button ? 

Verstuurd vanaf mijn iPhone

**Comment by nlrb** [comment]
@rhannink I've submitted https://github.com/athombv/homey-apps-sdk-issues/issues/47 with Athom for the device setting error
@mruiter The button is already in the json, but you only see it in once published in the app store 😄 
I'll start working on updating the docs.

**Comment by mruiter** [comment]
i see. but the button isnt showing in the mobile version of the appstore. only on my laptop.
so much for going all mobile as a statement from arom 🙈

Verstuurd vanaf mijn iPad

**Comment by konradwalsh** [comment]
since the latest version, mine is crashing on most arms/disarms

I assume you get the crash reports?

**Comment by nlrb** [comment]
@konradwalsh Nope, no crash reports. It has to be installed from the app store to get those. Don’t get crashes myself, so curious to know what is causing that.

**Comment by konradwalsh** [comment]
Hope this helps

![screenshot_20190206-222757_homey](https://user-images.githubusercontent.com/7996482/52378049-8ea54900-2a5e-11e9-9718-65a623853577.jpg)

**Comment by nlrb** [comment]
@konradwalsh You are not running the latest code. Please use the latest updates.

**Comment by Brendvm** [comment]
Hi, is there allready any plan for this version to hit te app store? Any news? 

Many thanks!

**Comment by nlrb** [comment]
@Brendvm Still no feedback from Athom on https://github.com/athombv/homey-apps-sdk-issues/issues/47. That will need to be resolved first.

**Comment by nlrb** [comment]
Guess this will never be released...

**Comment by nlrb** [comment]
[silly_demo.zip](https://github.com/nlrb/com.visonic.powermax/files/2945221/silly_demo.zip)
Can someone test this example app on v2 to see that it generates the same error (hopefully this is simple enough for Emile to understand)?

**Comment by Brendvm** [comment]
I hope there is someone who can test. 

Otherwise, if someone can talk me through on how to install and test i can help. But i simply have no idea...

**Comment by nlrb** [comment]
@Brendvm You can find instructions on how to install via CLI on [Youtube](https://www.youtube.com/watch?v=JnjAyWKSEIE). Testing is just 1) pairing a silly device and 2) updating the device settings.

**Comment by Brendvm** [comment]
Looks easy. I will find some time tomorrow evening to test. I'll keep you updated.

**Comment by rhannink** [comment]
@nlrb,

Just installeer the silly app ;-) Created one silly alarm and changed the Advanced settings and I got the Same error:

![image](https://user-images.githubusercontent.com/1661824/54160220-414a3c00-444f-11e9-89d8-1de7975b6982.png)

Is there a correct PIN code to enter ???

**Comment by konradwalsh** [comment]
> [silly_demo.zip](https://github.com/nlrb/com.visonic.powermax/files/2945221/silly_demo.zip)
> Can someone test this example app on v2 to see that it generates the same error (hopefully this is simple enough for Emile to understand)?
just installed it now

**Comment by konradwalsh** [comment]
I had the same behaviour 


I tried saving settings without a pin
and with a pin
used 9999 , 1111, 0000

**Comment by nlrb** [comment]
@rhannink, @konradwalsh Thanks for testing. But does it also give an error in case you entered the right pin code (='270614' - guess what date that was...)?

**Comment by konradwalsh** [comment]
![image](https://user-images.githubusercontent.com/7996482/54161011-dbf34c80-4448-11e9-80b1-636e5d5bf214.png)


That was the date you created your Vera/MIOS Visonic Plugin

**Comment by nlrb** [comment]
@konradwalsh Thanks for testing! That is the image I needed.
(BTW: It is the date Homey was successfully funded on KS)

**Comment by rhannink** [comment]
@nlrb ,

Same here:

![IMG_4128](https://user-images.githubusercontent.com/1661824/54178593-aa08d700-4496-11e9-8ad8-5c33a59ff453.PNG)

**Comment by rpbras** [comment]
Beste Ramon,

Al zeer geruime tijd gebruik ik je Visonic app om via Homey mijn alarm te
bedienen. Ik gebruik zelfs nog versie 1.40 welke uitstekend functioneert.

Ik verwacht dat V5 van Homey binnenkort uitkomt. Ik wil hier pas naar
overstappen als ik 100 % zeker weet dat de Visonic app onder deze versie
werkt.
Kun je hier iets over zeggen?

Alvast bedankt voor je reactie.

Mvg,
Raymond Bras

**Comment by phgmhendrix** [comment]
@rpbras , @nlrb heeft me al laten weten dat de huidige (meest recente) versie perfect werkt in v5. Hij adviseerde me ook om Homey nog niet te updaten 🙂

**Comment by nlrb** [comment]
Hi Raymond,

Peter was me te snel af, maar heeft helemaal gelijk. Voor de Visonic app is er geen verschil aangezien v2 API apps nog gewoon worden ondersteund.

Grtz,
-Ramón

**Comment by mruiter** [comment]
Werkt perfect op v5

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Werkt perfect op v5


Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
En v5 is stabieler dan v4 dus ik zou eerder vorig jaar dan morgen over stappen naar v5 
 😂 en draai meerdere homeys met 1 voorzien van 270 devices .
Dus genoeg getest zou ik zeggen om dit te kunnen stellen 

Verstuurd vanaf mijn iPhone
