### ISSUE TITLE
how to connect powermax to Homey

### ISSUE THREAD

**Issue by rupkerupke** [nlrb/com.visonic.powermax#30]
Hello,

I have the  Visonic (dual) RS-232 Interface Module in combination with a RS-232 to Ethernet module.
I need some help with further installation:
1) Which output of the Visonic modules is to be used (the PL/PC connection or the CELL/PC connection)
2) Do I need to change settings inside the powermax before the RS-232 unit becomes operational?
I connect the visonic RS-232 module to the USR-TCP232 module.
3) how do I find the IP adres of the RS-232 ethernet module?

thanks,
Rob

**Comment by nlrb** [comment]
Hi Rob,

1. PL/PC (PL = PowerLink)
2. No
3. See the manual of the USR-TCP-232. You can also download a tool for this from their website.

Grtz,
-Ramón

**Comment by rupkerupke** [comment]
Hi Ramón,

thank you for the answers.
I find the IP adres of the USR-TCP-232 module. 
Should I use static IP adres or DHCP inside the USR-TCP-232 module?
I now set it to DHCP. I find the internetadres, what is the value for :poort I should use?
Unfortunately my Homey does not find the powermax yet.
Are there any settings i need to do in the USR-TCP-232 module?

Rob

**Comment by rupkerupke** [comment]
Are there any settings I need to do in the USR-TCP-232 module?

**Comment by nlrb** [comment]
Static is safer - otherwise you need to change the IP address in Homey each time the module gets a new IP. For settings see #17.

**Comment by rupkerupke** [comment]
I set the IP adres fixed and use this IP adres to search for the powermax with the Homey.
I also set the settings of the post #17:
Parity/data/stop: NONE 8 1
Baudrate: 9600
Work mode: TCP Server

I also checked the pin layout of the cable.

I get acces to the powermax connecting it directly tot he PC using the visionc remote programming application.
I get acces to the USR-TCP232-302 module when I enter its IP nr in the browser.

In the USR-TCP232-302 module I set the port nr.  and used this value as port nr in the homey settings.
Unfortunately not with the desired result.
I must be overseeing something, or are there any other settings in the USR-TCP232-302 or Powermax I  need to do?

Please advice....

**Comment by nlrb** [comment]
If you have the 302 then watch the pinout (look at the docs). You cannot use a normal gender changer with that. Otherwise post some pics of how it is connected.

**Comment by rupkerupke** [comment]
I have cheched the pinout and you are right the normal gender changer is not OK to use.
I used the wrong one and needed to swap pin 2 and 3.

The Pin layout of the powermaxpro connector seems too be like described in post #17:
Pinout:
RJ45 (8 pin) - DB9 (F)
3 (TXD) black - 2 (RXD)
5 (GND) green - 5 (GND)
6 (RXD) yellow - 3 (TXD)

The input of the USR-TCP232-302 is:
DB9 Female:
2: TXD
3: RXD
5: GND.

So I connected the
green wire to pin 5, 
black wire to pin 3
yellow wire to pin 2

Other settings in USR-TCP232-302 :

![image](https://user-images.githubusercontent.com/46223876/50550560-28fdba00-0c73-11e9-8aa6-fbc7f9be39ca.png)

![image](https://user-images.githubusercontent.com/46223876/50550548-01a6ed00-0c73-11e9-92f5-46f108ba1b3b.png)

![image](https://user-images.githubusercontent.com/46223876/50550571-3fa41100-0c73-11e9-90a5-551a0b79558f.png)

![image](https://user-images.githubusercontent.com/46223876/50550579-6cf0bf00-0c73-11e9-8262-715ff08dbf5a.png)

In Homey app tried the following IPadresses:
192.168.1.89:0
![image](https://user-images.githubusercontent.com/46223876/50550592-b2ad8780-0c73-11e9-9f8b-5eaf9caee3b8.png)

After appr. 20 seconden search the result as shown below:
![image](https://user-images.githubusercontent.com/46223876/50550601-d244b000-0c73-11e9-977b-23a34290145f.png)

If I try IP adres::
192.168.1.89:80. Then the homey reports immediatly the Powermax  can not be found.

**Comment by nlrb** [comment]
Try configuring another port number, e.g. 70. Port 80 is the default for http - so you now have a port conflict (you have also configured the web interfce on port 80).

**Comment by rupkerupke** [comment]
thank you once again!
Progress has been made.
I changed the port nr and the Homey now sometimes sees the powermax:
![image](https://user-images.githubusercontent.com/46223876/50552069-01671b80-0c8c-11e9-8d42-795fdfa8ff6c.png)
After pressing the "install plnk" on the powermax unit. 
![image](https://user-images.githubusercontent.com/46223876/50552092-51de7900-0c8c-11e9-908d-8374969955c0.png)

It continued with:
![image](https://user-images.githubusercontent.com/46223876/50552089-4723e400-0c8c-11e9-9b17-2bdb0eae3bd7.png)

No further progress was visible on the Homey, even after long waiting time.

The HW version of my Powermax was shown in the visonic remote programming application:
![image](https://user-images.githubusercontent.com/46223876/50552096-66bb0c80-0c8c-11e9-8355-17149e38e369.png)
I am not aware of having a powerlink module inside my powermax unit

**Comment by nlrb** [comment]
I have the same version panel myself, but that one does not support auto enrollment. I have to do that from the panel menu.

**Comment by rupkerupke** [comment]
I searched for the "panel menu" on my powermax. I can not find it. 
I also serached for it in the installation manual. Also no result.
Could you please advice once more?

**Comment by nlrb** [comment]
![powerlink](https://user-images.githubusercontent.com/11725674/50557838-3c4b6c80-0ce9-11e9-9195-fe8951541ee7.png)

**Comment by rupkerupke** [comment]
helaas krijg ik de powerlink niet ingesteld. Ik heb het menu als hierboven geprobeerd. Ik krijg iedere keer de lange pieptoon.
Menu's die ik krijg:

Via installatiemenu:
1: install.PLNK
(OK) = inleren
Daarna volgt de lange pieptoon

via gebruikersmenu:
pwrlink opties
install powerlink
(OK) = inleren
Daarna volgt de lange pieptoon

Homey geeft ondertussen
![image](https://user-images.githubusercontent.com/46223876/50562773-569c3f00-0d17-11e9-9d93-9dcb1cf16701.png)

**Comment by nlrb** [comment]
Is er wellicht eerder een andere PowerLink geregistreerd geweest? Anders moet je die eerst verwijderen (via dezelfde menu optie in het paneel).

**Comment by nlrb** [comment]
![image](https://user-images.githubusercontent.com/11725674/50563882-eeeaf180-0d20-11e9-9b55-3cda1b70b71d.png)
![image](https://user-images.githubusercontent.com/11725674/50563886-fa3e1d00-0d20-11e9-91e0-f92c3e458dab.png)

**Comment by rupkerupke** [comment]
vandaag weer verder gegaan met proberen.
Ik heb de powermax gereset naar de fabrieksinstellingen.  Ik krijg daarna nog steeds geen verbinding.
Ik krijg de powermax module niet "ingeleerd".

Ik vraag me af of ik wel de goede hardware heb.
In mijn powermax basistation zit geen powerlink module zoals beschreven in "stap3"van onderstaand plaatje:
![image](https://user-images.githubusercontent.com/46223876/50735024-44535280-11a8-11e9-806d-c804bbc66737.png)

Ik ga vanaf de dual RS232 module (zie stap 5 van bovenstaand plaatje) via de PL/PC uitgang (linker connectie op DUAL RS232 module) naar de RS232 aansluiting van de USR-TCP232-302 module. De ethernet zijde hiervan is verbonden met mijn router.

Op de powermax kom ik zowel via het menu van de gebruikersinstellingen als de installatiemodus in een menu  7.pwrlink opties.
dit menu bestaat uit 2 opties:
1: install. plnk
2: pwrlnk fout.
al ik bij  menu 1 op OK klik 
komt alleen het scherm:
(OK) = inleren
druk ik op OK dan volgt "moment aub..... enkele seconden later gevolgd door een lange pieptoon (erop duidend dat de installatie van de pwrlink niet gelukt is...

**Comment by rupkerupke** [comment]
correctie, het is nu toch gelukt!
oorzaak lijkt een slechte connector.

**Comment by nlrb** [comment]
Volgens mij heb je 30 seconden op het moment dat Homey gaat wachten op het inleren om de procedure uit te voeren op het paneel. Anders mislukt het. Voer je de procedure op het paneel direct uit wanneer Homey hierom vraagt?

**Comment by nlrb** [comment]
Top!

**Comment by rupkerupke** [comment]
oorzaak is inderdaad een slechte verbinding. de 9-polige male-male sub D stekker maakte slecht contact bij de USR module. 
Ik heb nu de female stekker verandert naar male zodat de tussenstekker niet meer nodig is. Nu werkt het meteen.
Ik kwam er toevallig achter nadat ik tegen de stekker aandrukte bij het nogmaals proberen in te leren. Nu ging de homey naar downloaden van data.

Ik ben blij dat het nu werkt.
@ nlrb, bedankt voor je support. Zonder jouw hulp was het niet gelukt!
