### ISSUE TITLE
Error when saving advanced settings in 2.0.0

### ISSUE THREAD

**Issue by rhannink** [nlrb/com.visonic.powermax#32]
When I try to save the advanced settings of the panel, I get an error (unable to save the settings, unknown error).

I can only send you a diagnostic report when the app is from the App Store. Not when installed via athom-cli

**Comment by rhannink** [comment]
![img_4042](https://user-images.githubusercontent.com/1661824/51748604-3a3cb980-20ad-11e9-924b-416edf7b2413.PNG)
![img_4043](https://user-images.githubusercontent.com/1661824/51748605-3a3cb980-20ad-11e9-8b60-19b0f51f4b80.PNG)
![img_4044](https://user-images.githubusercontent.com/1661824/51748606-3a3cb980-20ad-11e9-9025-a621ea53c77b.PNG)


Did some more testing. When I leave the master code blank I get in red (top of app) the message **(Geen pincode ingevuld, instellingen niet opgeslagen. er is een onbekende fout opgetreden [unkown error])**. (3e afbeelding)

When I enter the correct pincode I get **(apparaat instellingen bijgewerkt. Er is een onbekende fout opgetreden [unkown error])**. But it does seem to change and store all the advanced settings despite the uknown error. (1e afbeelding)

I the changed you code a bit and hardcoded the master code in the app.json file:

```
    "value": "1234"
```
I then deleted the entered master pincode (4x*) and then saved the settings again and I the got a green message: **Instellingen opgeslagen**  (2e afbeelding)

So it looks like it has something to do with entering the code in the app, maybe wrong type or something......

**Comment by nlrb** [comment]
Well, I hope you don't have a pin code stored in the device settings now... That is the whole trick here. I'm not using the regular path that saves *all* device settings, because you don't want the pin code to be stored! Hence I do generate an error towards Homey such that the settings are not stored when saving the settings:
```
    // Make sure Homey doesn't change the settings - we do that!
		callback(result.msg, null)
```
However, this should not be propagated to the user (and it never was).

**Comment by rhannink** [comment]
I am not completely sure what this all means....Athom did something wrong in their API's ?????

**Comment by rhannink** [comment]
I added some logging to the code which outputs the master code from the panel and the master code from the advanced settings screen. They are identical. So the problem is that Athom generates an error while there actually is no error....

But the why do I not get an error when I hardcode the master code .........

**Comment by nlrb** [comment]
You don't hardcode the pin code. The value in the `app.json` is just the default value.

**Comment by rhannink** [comment]
Did a little dive in the SDKv2 and in turns out that it should be:

```
    // Make sure Homey doesn't change the settings - we do that!
		callback(null, result.msg)
```

With that change, it works for me.....

**Comment by rhannink** [comment]
Only one small problem. If I change after saving the settings another parameter, I get the message that the pincode is not filled in, but there are still 4 * in the master code field. This suggests that the master code is filled in.

**Comment by nlrb** [comment]
No, don’t change that!! Now your pin code is saved in the device settings. This removes the whole security measure... You will now need to delete your panel device.

**Comment by rhannink** [comment]
I am lost...it shows again, I am no programmer...I am not good enough at NodeJS to fix these kind of problems. I hope you can fix it (with Athom).
