### ISSUE TITLE
Wrong detection of flood-sensor

### ISSUE THREAD

**Issue by phgmhendrix** [nlrb/com.visonic.powermax#37]
@nlrb 
I just did a complete logging session with a smoke detector (MCT-423) and a flood detector (MCT-550).
Both use the same sensortype 0x6a. Maybe we should start taking the zonetype into account for proper identification.
There is a lot of overlap here and there.

![20190818_121436745_iOS](https://user-images.githubusercontent.com/11439882/63224370-5330c780-c1c3-11e9-88f7-6e2589a2e149.jpg)
![20190818_121838329_iOS](https://user-images.githubusercontent.com/11439882/63224372-65ab0100-c1c3-11e9-8765-688ca6eed21d.jpg)

**Comment by nlrb** [comment]
Removed the log file as there was sensitive info in there.

**Comment by phgmhendrix** [comment]
Thanks, already removed some info...not enough apparently.
Do you need me to create a new logfile?

**Comment by nlrb** [comment]
No need for a log file. If you can just give me the types with ids for the unknowns that would be good.
Annoying that the same id is used for multiple sensor types. For automatic detection the only option is then indeed to take the zonetype into account.

**Comment by phgmhendrix** [comment]
Here it is... will this suffice?
[logging.log](https://github.com/nlrb/com.visonic.powermax/files/3566947/logging.log)

**Comment by nlrb** [comment]
Can you tell me which sensors you have in Zone 2, 4, 5 & 6?

**Comment by phgmhendrix** [comment]
Sorry, been very busy...no time for my Homey.
Will try to do a sensor-sweep next weekend.

**Comment by phgmhendrix** [comment]
Zones 2 and 4 are MCPIR-3000 (verified by pictures). If my administration is correct, zones 5 and 6 are the same.
![20191211_203617321_iOS](https://user-images.githubusercontent.com/11439882/70658955-5d3d7100-1c5f-11ea-9bb4-829f76cb5913.jpg)
![20191211_204142169_iOS](https://user-images.githubusercontent.com/11439882/70658979-6c242380-1c5f-11ea-9ec0-11c2cd012cfd.jpg)

**Comment by nlrb** [comment]
Assume this is solved now.
