### ISSUE TITLE
Hardware question for Powermax+

### ISSUE THREAD

**Issue by Vierdank** [nlrb/com.visonic.powermax#38]
Hello!
I have a Powermax+ working just fine. And I would like to use your lovely app to connect it to Homey. Primarily to make use of the PIRs for automation.

Now, I'm not a computer wizard and know very little of programming and network.
For what I understand I have to tap the Powermax for serial data using either the RS232-thing that is (still?) available on the market or a TTL-thing. And from there an adapter to transfer it to my network - you mention RS232 - Ethernet. Unfortunately I have a long and complicated run from the Visonic to nearest ethernet connection. So I was wondering if it works with a serial adapter RS232 - Wifi of some sort? Like, as an example, something like this: http://www.nordfield.com/serial-wifi-adapter

I would really appreciate your input and knowledge, since it would really facilitate for a novice like myself. And for many others as well, I would think...
All best

**Comment by nlrb** [comment]
Challenge is that you probably cannot buy the Visonic RS232 module anymore. Which would mean the TTL module is the only option. And that will need some DIY work. And of course there are wifi options for both RS232 as well as TTL modules. See #17 and #30.

**Comment by Vierdank** [comment]
Many thanks for your answer!
Will look after a used RS module.

All best
/Stefan
