### ISSUE TITLE
Sensors don’t work anymore after update

### ISSUE THREAD

**Issue by robje76** [nlrb/com.visonic.powermax#39]
After the update today (homey
2.0.3) the sensors doesn’t work anymore. 

Is there a solutions for this problem. 
I have got a lot of flows with the sensors. 

![80C041EB-5F0C-493B-9FDA-C432F5F28896](https://user-images.githubusercontent.com/58187510/69568465-f01db080-0fbb-11ea-9953-c0d1fb44ab17.jpeg)

**Comment by luccie007** [comment]
Here I have the same problem, only it's showing red triangles instead of
the loading sign.

Op ma 25 nov. 2019 19:44 schreef robje76 <notifications@github.com>:

**Comment by robje76** [comment]
I have uninstalled the app and reinstalled. The doorsensors are working again. But the infrared sensor is not recognized anymore

**Comment by robje76** [comment]
> Here I have the same problem, only it's showing red triangles instead of the loading sign. Op ma 25 nov. 2019 19:44 schreef robje76 <notifications@github.com>:
> […](#)
I also had the red triangles. But after restarting the app, I got the loading signs.

**Comment by nlrb** [comment]
Yes, v2 is indeed not backward compatible. We had a discussion about this (see https://github.com/nlrb/com.visonic.powermax/issues/29#issuecomment-450486409).
So either you need to use the old version of the app or re-install the sensors.

**Comment by robje76** [comment]
Re-installed the sensors but the infrared is not recognized. 

How can i install the old version??

**Comment by phgmhendrix** [comment]
Same problem with my colleague... I have not yet updated, but we are trying to debug and find the problem. (but it's hist first Homey debugging session)

**Comment by nlrb** [comment]
@robje76 
Hmm, seems that Athom has removed the option in the new app store to install an old version.
You can install the old version via CLI. The code in the main branch is the old version.

**Comment by phgmhendrix** [comment]
@nlrb should the old version of the master branch work?

**Comment by nlrb** [comment]
@phgmhendrix Yes, the master branch has v1.4.0 of the app. The new version is in the v2 branch.

**Comment by robje76** [comment]
> @robje76
> Hmm, seems that Athom has removed the option in the new app store to install an old version.
> You can install the old version via CLI. The code in the main branch is the old version.

I have no idea how I can get the master branch code

**Comment by nlrb** [comment]
Go to the Code tab and click Clone or download.
There is a nice youtube video how to install apps via CLI.

**Comment by konradwalsh** [comment]
I have reinstalled everything
Factory reset Alarm Panel
Remove connection to homey and started over..


The app store version doesnt see my Motion Sensors as stated above.. just door sensors.
The MASTER version does see everything and allows me to add everything but then the panel becomes unresponsive.
Installing MASTER, Adding everything and Updating to store version.. i lose sensors and can only re-add door sensors

As anyone else found a method to get everything working?

Prior to my reinstall.. I was on App Store latest and had ALL sensors

**Comment by nlrb** [comment]
Can you run the 'sdk2' branch version (which is the app store version) via CLI and send me the logging?

**Comment by konradwalsh** [comment]
Terrible way to provide a log.. sorry.. its in  next post

Interestingly, the log says it sees these, which is accurate:

` 2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 1 (Front door): Delay 1 (chime = Off ; sensor type = 96 [Magnet, MCT-302T])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 2 (Back door): Home Delay (chime = Off ; sensor type = 95 [Magnet, MCT-302])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 3 (Living room): Perimeter (chime = Off ; sensor type = 97 [Magnet, MCT-302])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 5 (Hallway motion): Interior-Follow (chime = Off ; sensor type = 74 [UNKNOWN (0x74), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 6 (Kitchen): Interior (chime = Off ; sensor type = 74 [UNKNOWN (0x74), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 7 (Upstairs): Interior (chime = Off ; sensor type = a4 [UNKNOWN (0xa4), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 8 (Living room): Interior (chime = Off ; sensor type = b3 [UNKNOWN (0xb3), undefined])`

**Comment by konradwalsh** [comment]
[Log from PowermaxPro.txt](https://github.com/nlrb/com.visonic.powermax/files/4010076/Log.from.PowermaxPro.txt)

**Comment by nlrb** [comment]
Removed the log as it contains pin codes etc.

Can you tell me which sensors you have in zones 5, 6, 7 & 8?

```
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 5 (Hallway motion): Interior-Follow (chime = Off ; sensor type = 74 [UNKNOWN (0x74), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 6 (Kitchen): Interior (chime = Off ; sensor type = 74 [UNKNOWN (0x74), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 7 (Upstairs): Interior (chime = Off ; sensor type = a4 [UNKNOWN (0xa4), undefined])
2019-12-30 14:49:14 [log] [ManagerDrivers] [powermax] [0] Zone 8 (Living room): Interior (chime = Off ; sensor type = b3 [UNKNOWN (0xb3), undefined])
```

**Comment by konradwalsh** [comment]
i see the log says sensor type = 74 , a4, a3
But they are all the same motion sensors.

Model: NEXT K9-85 T DD MCW(868)

When added with version 1.40 MASTER branch.. they are seen as what they are

**Comment by nlrb** [comment]
Thanks, I'll add this to the table.

**Comment by konradwalsh** [comment]
Great,,
Let me know if you want me to test anything for you.


Side question: What is your favourite online gadget shop? Like PiHut etc?

**Comment by nlrb** [comment]
Try the latest commit.

**Comment by konradwalsh** [comment]
yep, this works 100%

Thanks for your hard work as always..

please tell me your favourite online store or your paypal address

**Comment by nlrb** [comment]
Submitted for test: https://homey.app/a/com.visonic.powermax/test/

Great to hear your panel is working again!

BTW: there is a donate link in the app store nowadays if you really want to...

**Comment by konradwalsh** [comment]
Sent you something that might buy you a beer and pizza... or whatever you enjoy..

Thanks again!

**Comment by phgmhendrix** [comment]
Great... my donation is also on the wire!

**Comment by nlrb** [comment]
Thanks for the help and donations guys! Let me know if there are more things we can improve.
