### ISSUE TITLE
Connect Visonic PowerMaxPro when Powerlink module present

### ISSUE THREAD

**Issue by PaulTelg** [nlrb/com.visonic.powermax#40]
Hi,
 
I have a Powerlink2 Internet module installed in the Visonic2 PowerMaxPro.  I can interact with the Visionic Webservice via the browser on the standard HTTP-port. But I like to control the Visonic also via the Homey app and downloaded your app.

Is there a way to connect your Visonic Homey app directly to the Powerlink2 module so it can read all the required information?  At this moment I can't bypass the first step, Add Paneldevice with the correct IP-address and port combination.

I saw you're using the telnet port during the initial panel setup so I was wondering if i could access on this port my Visonic PowerMaxPro. I tested this from the command-window  and can connect to the Visonic PowerMaxPro via the telnet command. I got a login and after that the password, However I don't know what the default username and password is to access the PowerMaxPro via telnet. 

The first step in my fault domain isolation is the following:
Does you app support adding the PowerMaxPro via a Powerlink2 module? 
I hope so because then I don't need to buy a Dual RS232 Interface module , if still possible, and RS232-Ethernet converter. And if it is possible what are the IP-address/Port combination, telnet port, and more important the username/password combination you use. 

I hope you can help. It seems that you made a nice Visonic app.

Best Regards

**Comment by nlrb** [comment]
Hi Paul,

The app only support controlling the Visonic via serial communication, not via a Powerlink. It sort of replaces the functionality of the Powerlink and saves you the cost of adding that part. You also cannot use the Powerlink together with controlling it via RS232/Homey app (there can only be one 'master' on that port).

Best regards,
-Ramón.
