### ISSUE TITLE
Visonic powermaster system reset

### ISSUE THREAD

**Issue by gowiththeflows** [nlrb/com.visonic.powermax#45]
My panel seems to reset every 4th hour or so panel status goes from 'downloading' to current state eg 'disarmed' followed by the confirmation chirp tone from the panel. Connected with RS-232 to Ethernet module. Worked the fine the first couple of days.

**Comment by nlrb** [comment]
Connected via wifi I guess? Probably the connection drops. When it re-establishes a connection it will do a download again.

**Comment by gowiththeflows** [comment]
The module is connected with cable. Then i will have to check cables and switches. Thank you for the tip.

**Comment by gowiththeflows** [comment]
This issue can be closed. It was a problem with the gprs connection on the control panel and a system failure that triggered a connection reset every fourth hour.
