### ISSUE TITLE
Upgrade for new homey pro 2023

### ISSUE THREAD

**Issue by yvoren** [nlrb/com.visonic.powermax#48]
Wil there be a upgrade available for homey pro 2023 ?

**Comment by phgmhendrix** [comment]
> Wil there be a upgrade available for homey pro 2023 ?

We are working on an upgrade. Yesterday I successfully deployed a new version on my P23 that was mainly created by @phict.
@nlrb is already reviewing it.

**Comment by yvoren** [comment]
Hi Peter,Thats great news, hopefully everything is going to work on the new homey.Met vriendelijke groet,René Slisser.Op 20 mrt. 2023 om 09:04 heeft Peter Hendrix ***@***.***> het volgende geschreven:﻿

Wil there be a upgrade available for homey pro 2023 ?

We are working on an upgrade. Yesterday I successfully deployed a new version on my P23 that was mainly created by @phict.
@nlrb is already reviewing it.

**Comment by nlrb** [comment]
Changes are available in https://github.com/nlrb/com.visonic.powermax/tree/sdk3.

**Comment by yvoren** [comment]
Hi Peter,Any idea when the sdk3 upgrade for the powemax wil be availabe? I want to use my new homey pro 2023. But only if the powermax can be used.Met vriendelijke groet,René Slisser.Op 22 mrt. 2023 om 17:59 heeft Slisser, Rene ***@***.***> het volgende geschreven:﻿Hi Peter,Thats great news, hopefully everything is going to work on the new homey.Met vriendelijke groet,René Slisser.Op 20 mrt. 2023 om 09:04 heeft Peter Hendrix ***@***.***> het volgende geschreven:﻿

Wil there be a upgrade available for homey pro 2023 ?

We are working on an upgrade. Yesterday I successfully deployed a new version on my P23 that was mainly created by @phict.
@nlrb is already reviewing it.

**Comment by phgmhendrix** [comment]
Due to my work I haven't been able to do a lot of work, hopefully I can get something done this week. But @yvoren, you could test things already with the branch of @nlrb. The basics work like a charm.

**Comment by phgmhendrix** [comment]
Just tested the latest version of @nlrb a bit better and this one seems quite complete already. I am going to give it a go on the new Pro 2023.

**Comment by nlrb** [comment]
It should be complete indeed 😁.

**Comment by yvoren** [comment]
Hi,Good to read, but when wil it be available in Homey pro apps store ?Met vriendelijke groet,René Slisser.Op 23 apr. 2023 om 22:36 heeft Ramón Baas ***@***.***> het volgende geschreven:﻿
It should be complete indeed 😁.

**Comment by yvoren** [comment]
How can you implement it on HP23 whit out the Homey pro Apstore, can it be installed directly from here.
How can I do that

**Comment by phgmhendrix** [comment]
> How can you implement it on HP23 whit out the Homey pro Apstore, can it be installed directly from here. How can I do that

Hi @yvoren , it is not that difficult, below a few steps.
- Install Homey developer tools. Instructions via [https://tools.developer.homey.app/](https://tools.developer.homey.app/) (npm install -g homey).
- Pull the proper code from @nlrb to a directory on your disk. [https://github.com/nlrb/com.visonic.powermax/tree/sdk3](https://github.com/nlrb/com.visonic.powermax/tree/sdk3)
- Open a command prompt and go to that folder.
- Type: homey app install

I wrote this from the top of my head, but it should roughly be that. Feel free to send me a connection request via [LinkedIn](https://www.linkedin.com/in/hendrixpeter/) or [Facebook](https://www.facebook.com/peter.hendrix.140) so I can help you a bit more via chat.

**Comment by nlrb** [comment]
You should be able to install the test version from the appstore: https://homey.app/en-us/app/com.visonic.powermax/Visonic-PowerMax/test/

**Comment by yvoren** [comment]
Hi,If i want to arm or disarm or partily arm the alarm from homey, i get calback is not a function.Is this still work in progress ?Met vriendelijke groet,René Slisser.Op 30 apr. 2023 om 12:00 heeft Ramón Baas ***@***.***> het volgende geschreven:﻿
You should be able to install the test version from the appstore: https://homey.app/en-us/app/com.visonic.powermax/Visonic-PowerMax/test/

**Comment by nlrb** [comment]
Thanks for testing @yvoren. Indeed, it looks like not everything was migrated to SDK v3 (and tested). The flows and device settings still needed an update. I've created a new test version (3.0.1).

**Comment by yvoren** [comment]
Hi Also when i want tot exclude a pir or window/door contact i get the message callback is not a function.Met vriendelijke groet,René Slisser.Op 30 apr. 2023 om 21:09 heeft Ramón Baas ***@***.***> het volgende geschreven:﻿
Thanks for testing @yvoren. Indeed, it looks like not everything was migrated to SDK v3 (and tested). The flows and device settings still needed an update. I've created a new test version (3.0.1).

**Comment by nlrb** [comment]
@yvoren Thanks again for testing! Should be fixed in test version 3.0.2. Let me know if you find anything else :-).

**Comment by yvoren** [comment]
Hi Ramon,

Based on location I activate a flow to arm or disarm the alarm, on the PowerMax the alarm does not gives a result activated or deactivate .
In other words I does not follow the real condition.

Or should I rebuild al my flows with the new PowerMax flow charts ?

**Comment by nlrb** [comment]
Hi @yvoren Have you tested the flows? Probably you will get an error message. By default the device setting is such that you are not allowed to arm/disarm the panel via Homey (due to security). However, there was a bug in the v2 version that this setting was ignored. I’ve fixed that. So it might be as simple as updating the device setting to allow arming & disarming.
