### ISSUE TITLE
can't find panel in homey

### ISSUE THREAD

**Issue by herbie65** [nlrb/com.visonic.powermax#49]
I used to use the power link.
in installer model there is no menu option "7 pwlnk" so i can't deinstall it.
i removed it and installed the USR TCP232 according this pins.
![IMG_2582](https://github.com/nlrb/com.visonic.powermax/assets/47215018/a70b86f4-2e97-4877-98d9-3d4e1d1a8bca)
I can connect to the web interface of the USR-TCP232\
however homey can't find it....
anyone?

**Comment by nlrb** [comment]
Hard to tell what is wrong like this. Would be helpful if you would share photos and screenshots.
Lots of things could be wrong, e.g. baudrate settings, mixing up rx/tx etc.

**Comment by herbie65** [comment]
Reinstalled, did everything the same. Now it works OK'ish))
