### ISSUE TITLE
sensors not working when disarmed

### ISSUE THREAD

**Issue by herbie65** [nlrb/com.visonic.powermax#50]
I wild like to use the Visonic sensors to trigger flows.
However all the sensors don't seem to react in Homey. At least when the alarm is disarmed, However i do like to use the sensors also when the panel is disarmed.
Is this possible?
Am i doing something wrong?
I use doorcontact MCT-302
PIR K-940 MCW
I used a simple flow to experiment, but nothing happens.

<img width="406" alt="Scherm­afbeelding 2023-07-27 om 23 53 07" src="https://github.com/nlrb/com.visonic.powermax/assets/47215018/2e038cae-efdd-49f2-a80c-bfc26fec6d94">
<img width="1003" alt="Scherm­afbeelding 2023-07-27 om 23 52 46" src="https://github.com/nlrb/com.visonic.powermax/assets/47215018/4390ca6c-755e-49bf-8768-6e5da350725c">
<img width="893" alt="Scherm­afbeelding 2023-07-27 om 23 55 10" src="https://github.com/nlrb/com.visonic.powermax/assets/47215018/a01337c7-6f50-4858-b117-1278786cf489">

**Comment by nlrb** [comment]
The PowerMaster (in contrast to the PowerMax) shuts off the sensors when the alarm is not armed. This to extend battery life. I’ve read somewhere that there is a setting in the alarm for the sensor to not go to sleep though.
